# SpectaQL Configuration

introspection:
  # URL of the GraphQL API
  url: https://6db1-105-235-134-149.ngrok-free.app/graphql

# Output directory for the generated documentation
output: ./docs

# Title of the documentation
title: My GraphQL API Documentation

# Theme options (optional)
theme:
  # Available themes: 'light', 'dark', 'honey'
  name: dark
  # Customize colors (optional)
  colors:
    primary: '#3498db'
    secondary: '#2ecc71'

servers:
  - url: https://6db1-105-235-134-149.ngrok-free.app/graphql